### ISSUE TITLE
Knapper forbliver aktive ved død

### ISSUE THREAD

**Issue by TheZerker** [Jakobtottrup/optekSemester1#7]
Vagtens knapper bliver aktive og brugbare igen, mens tyvens døds animation afspiller

**Comment by Jakobtottrup** [comment]
Fixed and pushed
Added check on inactive buttons to see if # of instances obj_thief_death higher than 0 and if so, not change sprite.
AKA.
obj_button_inactive checks if # !obj_thief_death > 1{
 // change to button active
}
